name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release_NoDevExPrjs src\FbPacketCapture.sln
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FbPacketCapture_release_${{ github.sha }}
        path: |
          src\FbPacketCapture\bin\Release_NoDevExPrjs\net6.0
          src\FboxEventLogCollector\bin\Release\net6.0
